### ISSUE TITLE
Firmware is incomplete!

### ISSUE THREAD

**Issue by X3msnake** [makerbase-mks/MKS-DLP#2]
There are no instructions on how to compile and update the firmware and there seems to be missing all informations on the Altera FPGA 

was this supposed to be open source?  looks more like smoke and mirrors to me.

**Comment by Tibus** [comment]
Would like to get these informations too! 
Thanks

**Comment by X3msnake** [comment]
https://www.facebook.com/Photonsters/posts/1164054750715170
