### ISSUE TITLE
How can we build the firmware?

### ISSUE THREAD

**Issue by MakerMatrix** [makerbase-mks/MKS-DLP#3]
Interested in the DLP board and particularly having an open source firmware to work with.  But the firmware you posted has no instructions for compiling/installation.

**Comment by MS1987** [comment]
@MakerMatrix
1, The project can be built Using IAR Embedded Workbench.
2,  After generate the "bin" file , copy it to the usb and update the firmware of the mainboard .

**Comment by E-Studios** [comment]
> @MakerMatrix
> 1, The project can be built Using IAR Embedded Workbench.
> 2, After generate the "bin" file , copy it to the usb and update the firmware of the mainboard .

In other words nothing... IAR is super expensive... no hobbyist is going to buy or able to buy that. and the most alternatives are expensive too or only on a quote.

**Comment by ElmonResinWorks** [comment]
I've downloaded IAR Workbench on a trial, but it's ridiculously confusing, and clicking compile when having your project loaded throws a load of bugs and errors out anyway?

How can we use this functionally??

**Comment by whhx-open** [comment]
![image](https://user-images.githubusercontent.com/14251428/75602435-12b1ef00-5b00-11ea-97dd-c762f5e08026.png)
it Can be compiled with this IAR version.

**Comment by X3msnake** [comment]
@MakerMatrix has forked the firmware into Photonsters github and added documentation on how to install and compile the firmware

https://www.facebook.com/Photonsters/posts/1164054750715170
