### ISSUE TITLE
What lib is needed expect QT4?

### ISSUE THREAD

**Issue by for-heart-peace** [makerbase-mks/MKS-DLP#4]

**Comment by for-heart-peace** [comment]
how to build mksdlp_slice_project? Can you write a issue to help me(rookie)?

**Comment by zhpt** [comment]
1. QT4.8
2.QtCreator4.10
3.install mingw32
you can follow this blog https://blog.csdn.net/win_turn/article/details/50465127

**Comment by for-heart-peace** [comment]
thank you very mush

**Comment by makerbase-mks** [comment]
close it?

**Comment by for-heart-peace** [comment]
close it!thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"makerbase"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月29日(星期六) 下午2:41
收件人:&nbsp;"makerbase-mks/MKS-DLP"<MKS-DLP@noreply.github.com&gt;;
抄送:&nbsp;"CLX"<957311501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [makerbase-mks/MKS-DLP] What lib is needed expect QT4? (#4)




close it?
